version: '3'

services:

  stock-strategy-service:
    image: stock/stock-strategy-service:latest
    hostname: stock-strategy-service
    depends_on:
      - daily-stock-service
      - weekly-stock-service

    ports:
      - 6969:8080
      - 6666:80

  weekly-stock-service:
    image: stock/weekly-stock-service:latest
    hostname: weekly-stock-service
    depends_on:
      - daily-stock-service

    ports:
      - 8989:8080
      - 8888:80

  daily-stock-service:
    image: stock/retrieve-stock:latest
    hostname: restrive-stock-api
    depends_on:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - manager
      - mongo
      - mongo-express

    ports:
      - 8080:8080
      - 80:80

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ports:
      - 22181:2181
    volumes:
      - /Users/vrushankjoshi/kafka/pub-technology/zookeeper/data:/var/lib/zookeeper/data
      - /Users/vrushankjoshi/kafka/pub-technology/zookeeper/datalog:/var/lib/zookeeper/log

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafkabroker1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkabroker1:9092,PLAINTEXT_INTERNAL://mylocalmachine:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - /Users/vrushankjoshi/kafka1/pub-technology/kafka/data:/var/lib/kafka/data
    restart: always

  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafkabroker2
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkabroker2:9092,PLAINTEXT_INTERNAL://mylocalmachine:39092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    restart: always

  manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
    restart: always



  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    volumes:
      - /Users/vrushankjoshi/mongodb/data/:/data/db/
      - /Users/vrushankjoshi/mongodb/log/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb-data:
    driver: local
    name: mongodb-data
  mongodb-log:
    driver: local
    name: mongodb-log
